version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.spockframework:spock-core
    versions:
    - ">= 1.3-groovy-2.a, < 1.4"
  - dependency-name: net.bytebuddy:byte-buddy
    versions:
    - 1.10.19
    - 1.10.20
    - 1.10.21
    - 1.10.22
  - dependency-name: com.gradle.plugin-publish
    versions:
    - 0.12.0
    - 0.13.0
  - dependency-name: org.postgresql:postgresql
    versions:
    - 42.2.18
    - 42.2.19
