version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk

    - image: circleci/postgres:10
      environment:
        POSTGRES_USER: wanko_user
        POSTGRES_PASSWORD: wanko_pass
        POSTGRES_DB: wanko_db

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        - v1-dependencies-

    - run:
        name: Download dependencies
        command: ./gradlew dependencies

    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}

    - run:
        name: Wait for db
        command: dockerize -wait tcp://localhost:5432 -timeout 1m

    - run:
        name: run tests
        command: ./gradlew test

    - store_test_results:
        path: ~/repo/build/reports
        destination: reports

  deploy:
    docker:
    - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - checkout

    - run:
        command: |
          ./gradlew publishPlugins                            \
            --exclude-task test                               \
            -Pgradle.publish.key=${GRADLE_PUBLISH_KEY}        \
            -Pgradle.publish.secret=${GRADLE_PUBLISH_SECRET}

    - store_artifacts:
        path: ~/repo/build/libs
        destination: libs

workflows:
  version: 2
  build_deploy:
    jobs:
    - build
    - Deploy_Approval:
        type: approval
        requires:
        - build
        filters:
          branches:
            only: /v.*/
    - deploy:
        requires:
        - Deploy_Approval
